name: Java CI Pipeline

# Trigger (kích hoạt) quy trình này mỗi khi có code mới đẩy lên nhánh main
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest # Chạy trên máy chủ Ubuntu ảo của GitHub

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven' # Hỗ trợ cache để build nhanh hơn ở các lần sau

      - name: Build and Test with Maven
        run: mvn clean verify package

      - name: Upload Artifact (Lưu trữ file build)
        uses: actions/upload-artifact@v3
        with:
          name: compiled-project-jar
          path: target/*.jar